name: Continuous Integration with GitHub Actions

on:
  push:
    branches: 
      - main
      - developer
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Eureka Naming Server Container Image
      working-directory: ./devhotel-naming-server
      run: mvn spring-boot:build-image -DskipTests

    - name: Build API Gateway Container Image
      working-directory: ./devhotel-api-gateway
      run: mvn spring-boot:build-image -DskipTests

    - name: Build Room Service Jar
      working-directory: ./room-service
      run: mvn clean package -DskipTests

    - name: Build User Service Jar
      working-directory: ./user-service
      run: mvn clean package -DskipTests
        
    - name: Docker Compose Build
      run: docker-compose build
